// Чек лист: 2 итерация
### Positive: Пополнение баланса корректной суммой
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 6,
  "balance": 100.00
}

### Negative: Пополнение баланса некорректной суммой (<0.01)
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 6,
  "balance": -0.01
}

### Negative: Пополнение баланса некорректной суммой 0
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 6,
  "balance": 0
}

### Negative: Пополнение баланса некорректной суммой >5000.01
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 6,
  "balance": 5000.01
}

### Negative: Попытка пополнить чужой аккаунт
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 7,
  "balance": 100
}

### Negative: Попытка пополнить несуществующий аккаунт
POST http://localhost:4111/api/v1/accounts/deposit
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "id": 999,
  "balance": 100
}

### Positive: Изменение имени профиля корректное
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "Test Testov"
}

### Negative: Изменение имени профиля некорректное одно слово
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "Test"
}

### Negative: Изменение имени профиля некорректное (спецсимвол
PUT http://localhost:4111/api/v1/customer/profile
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "name": "John Smith!"
}

### Positive: Успешный перевод между счетами
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 6,
  "receiverAccountId": 7,
  "amount": 100.00
}

### Negative: Перевод некорректной суммы 0.01
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 6,
  "receiverAccountId": 7,
  "amount": -0.01
}

### Negative: Перевод некорректной суммы >10000.01
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 6,
  "receiverAccountId": 7,
  "amount": 10000.1
}

### Negative: Перевод суммы превышающей баланс
POST http://localhost:4111/api/v1/accounts/transfer
Content-Type: application/json
Authorization: Basic YWRtaW46YWRtaW4=

{
  "senderAccountId": 6,
  "receiverAccountId": 7,
  "amount": 100.00
}

